<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="TestData\**" />
    <EmbeddedResource Include="TestData\Json\Strings.jsoncfg" />
    <EmbeddedResource Include="TestData\Json\Strings.json" />
    <EmbeddedResource Include="TestData\Json\Strings_de.json" />
    <EmbeddedResource Include="TestData\Arb\Strings.arbcfg" />
    <EmbeddedResource Include="TestData\Arb\Strings.arb" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.*" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit" Version="2.9.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Tlumach.Base\Tlumach.Base.csproj" />
    <ProjectReference Include="..\..\src\Tlumach\Tlumach.csproj" />
    <ProjectReference Include="..\..\src\Tlumach.FluentValidation\Tlumach.FluentValidation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
