using System.Globalization;
using System.Reflection;

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Localization;

using Tlumach;
using Tlumach.Base;
using Tlumach.Sample;
using Tlumach.Extensions.Localization;

namespace Tlumach.Sample.DependencyInjection;

internal class Program
{
    private static async Task Main(string[] args)
    {
        // This sample uses two sets of translations - one coming from the sample.* files included as resources in this project
        // And another one coming from the Tlumach.Sample.Translation project.
        // This is done deliberately to illustrate the use of translation contexts.
        // See the comments in the code below for the details.

        // When TranslationManager is created in code like below, the parsers are not initialized automatically,
        // and the calls to the .Use() methods below are required.

        // In this sample, however, there also exists the autogenerated source code (in the Tlumach.Sample.Translation project) which initializes the parsers.
        // For this reason, the initialization below is commented out.
        /*
        ArbParser.Use();
        TomlParser.Use();
        */

        // This TranslationManager instance will access the strings in the sample.* files included in resources.
        TranslationManager manager = new TranslationManager(new TranslationConfiguration(Assembly.GetExecutingAssembly(), "sample.cfg", null, TextFormat.Arb));

        // Just to have a predictable culture in the sample - de-AT is chosen because it has a fallback to de-DE.
        CultureInfo.DefaultThreadCurrentCulture = CultureInfo.GetCultureInfo("de-AT");
        CultureInfo.DefaultThreadCurrentUICulture = CultureInfo.GetCultureInfo("de-AT");

        using var host = Host.CreateDefaultBuilder(args)
            .ConfigureServices(services =>
                services.AddTlumachLocalization(
                    // These are the default settings. They are used when you request IStringLocalizer without context.
                    options => { options.TranslationManager = manager; },

                    // Here, we specify the options for the IStringLocalizer created with "Strings" (actually, Tlumach.Sample.Strings) as a context.
                    // Tlumach.Sample.Strings comes from the Tlumach.Sample.Translation project.
                    // Here, it is used for illustrations.
                    //
                    // In your project, you can have different sets of translation files for different modules of your application.
                    // And in this situation, you can use classes that have a "TranslationManager" property as a context.
                    provider => provider.AddContext("Tlumach.Sample.Strings", new TlumachLocalizationOptions()
                        {
                            // This is only for illustration - if you comment out the assignment of the TranslationManager property,
                            // Tlumach will reach the Strings class of the Tlumach.Sample.Translation project and take TranslationManager from there.
                            TranslationManager = Strings.TranslationManager,
                        })
                )
            )
            .Build();

        // You can use untyped localizer and reach the strings in the resources of this project.
        var genericLocalizer = host.Services.GetRequiredService<IStringLocalizer>();
        Console.WriteLine(genericLocalizer["HelloName", "John Doe"]);

        // Typed localizer. It is created using the options, defined above.
        // Here, you reach the strings that come from the Tlumach.Sample.Strings class via its TranslationManager property.
        var localizer = host.Services.GetRequiredService<IStringLocalizer<Strings>>();

        // Using "Strings.Welcome" as a variable of type "TranslationUnit" and not as a string ensures
        // that there is no typo in the key which would lead to the translation not being found.
        // TranslationUnit has an implicit operator string which returns a key of the unit as a string.
        Console.WriteLine(localizer[Strings.Welcome]);

        await host.StopAsync();
    }
}
