<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
        <AdditionalFiles Include="../Shared/stylecop.json" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="[12.0.0, 13.0.0)" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.*" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Tlumach.Base\Tlumach.Base.csproj" />
        <ProjectReference Include="..\Tlumach\Tlumach.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Tlumach.FluentValidationTests" />
    </ItemGroup>

</Project>
