<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="../Shared/stylecop.json" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Tlumach.Blazor\Tlumach.Blazor.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Tlumach.BlazorTests" />
    </ItemGroup>

</Project>
