// <copyright file="StringAccessorTests.cs" company="Allied Bits Ltd.">
//
// Copyright 2025 Allied Bits Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// </copyright>

using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Reflection;

namespace Tlumach.Tests
{
    /// <summary>
    /// Tests of the nested class with string accessors that Generator emits when the createStringAccessors option is set.
    /// <para>The accessors exist so that the attributes that localize through a resource type and the name of a property, such as <see cref="DisplayAttribute"/> and <see cref="RequiredAttribute"/>, can be
    /// pointed at a class generated by Tlumach. Every test therefore checks the accessor the way the framework itself does.</para>
    /// </summary>
    [Trait("Category", "Generator")]
    [Trait("Category", "StringAccessors")]
    [Collection("Generator")]
    public class StringAccessorTests
    {
        private const string TestFilesPath = "../../../TestData/Generator";

        static StringAccessorTests()
        {
            // The generator carries its own copies of the parsers, so both sets have to be registered: the ones in Tlumach.Generator parse the configuration while the code is generated, and the ones in
            // Tlumach.Base parse the translation while the generated code runs.
            Tlumach.Generator.IniParser.Use();
            Tlumach.Generator.TomlParser.Use();
            Tlumach.Generator.ArbParser.Use();

            Tlumach.Base.IniParser.Use();
            Tlumach.Base.TomlParser.Use();
            Tlumach.Base.ArbParser.Use();
        }

        [Fact]
        public void ShouldNotGenerateAccessorsWhenOptionIsAbsent()
        {
            string source = Generate("Annotations.cfg", accessors: false);

            Assert.Equal(-1, source.IndexOf("class Texts", StringComparison.Ordinal));
            Assert.Equal(-1, source.IndexOf("CurrentValue", StringComparison.Ordinal));
        }

        [Theory]
        [InlineData("ValidConfigWithGroups.arbcfg")]
        [InlineData("Placeholders1.cfg")]
        [InlineData("Placeholders2.cfg")]
        [InlineData("FunctionStrings.cfg")]
        [InlineData("WebEncodedText.cfg")]
        [InlineData("NoUnits.cfg")]
        [InlineData("ExtraParams.cfg")]
        public void ShouldLeaveExistingConfigurationsUnchanged(string configFile)
        {
            string source = Generate(configFile, accessors: false);

            Assert.Equal(-1, source.IndexOf("class Texts", StringComparison.Ordinal));
        }

        [Fact]
        public void ShouldGenerateAccessorsAsPublicStaticStringProperties()
        {
            Assembly assembly = Compile(Generate("Annotations.cfg", accessors: true));

            // The two checks below are the ones that DisplayAttribute and ValidationAttribute perform themselves: the property must be of the type string and its getter must be public and static.
            PropertyInfo property = AccessorProperty(assembly, "Test.Translations.Strings+Texts", "emailLabel");
            Assert.Equal(typeof(string), property.PropertyType);
            Assert.True(property.GetMethod!.IsPublic);
            Assert.True(property.GetMethod.IsStatic);

            PropertyInfo nested = AccessorProperty(assembly, "Test.Translations.Strings+account+Texts", "emailRequired");
            Assert.Equal(typeof(string), nested.PropertyType);
            Assert.True(nested.GetMethod!.IsPublic);
            Assert.True(nested.GetMethod.IsStatic);
        }

        [Fact]
        public void ShouldProvideTextToDisplayAndValidationAttributes()
        {
            Assembly assembly = Compile(Generate("Annotations.cfg", accessors: true));
            PrepareManager(assembly);

            Type accessors = assembly.GetType("Test.Translations.Strings+Texts")!;

            DisplayAttribute display = new() { ResourceType = accessors, Name = "emailLabel" };
            Assert.Equal("E-mail", display.GetName());

            RequiredAttribute required = new() { ErrorMessageResourceType = accessors, ErrorMessageResourceName = "emailRequired" };
            Assert.Equal("The Address field is required.", required.FormatErrorMessage("Address"));
        }

        [Fact]
        public void ShouldFollowTheCultureOfTheManager()
        {
            Assembly assembly = Compile(Generate("Annotations.cfg", accessors: true));
            TranslationManager manager = PrepareManager(assembly);

            Type accessors = assembly.GetType("Test.Translations.Strings+Texts")!;

            // The very same attribute instances are reused on purpose: the framework caches the property it resolved but not the value it read, so a change of the culture has to be visible.
            DisplayAttribute display = new() { ResourceType = accessors, Name = "emailLabel" };
            RequiredAttribute required = new() { ErrorMessageResourceType = accessors, ErrorMessageResourceName = "emailRequired" };

            Assert.Equal("E-mail", display.GetName());
            Assert.Equal("The Address field is required.", required.FormatErrorMessage("Address"));

            manager.CurrentCulture = new CultureInfo("de");

            Assert.Equal("E-Mail-Adresse", display.GetName());
            Assert.Equal("Das Feld Address ist erforderlich.", required.FormatErrorMessage("Address"));
        }

        [Fact]
        public void ShouldGenerateTheSameAccessorsWithDelayedUnits()
        {
            string source = Generate("AnnotationsDelayed.cfg", accessors: true);

            // The delayed mode emits the unit as a property, and the accessor refers to it without any change of its own text.
            Assert.NotEqual(-1, source.IndexOf("private static Tlumach.TranslationUnit? _emailLabel", StringComparison.Ordinal));
            Assert.NotEqual(-1, source.IndexOf("public static string emailLabel => global::Test.Translations.Strings.emailLabel.CurrentValue;", StringComparison.Ordinal));

            // Nothing is created while the type is loaded: the static constructor assigns no unit, and the class of accessors has no static constructor at all. The leading indentation is what tells the
            // assignment in a static constructor apart from the one in the lazy getter, which assigns the backing field '_emailLabel'.
            Assert.Equal(-1, source.IndexOf("\n            emailLabel = new", StringComparison.Ordinal));

            Assembly assembly = Compile(source);
            PrepareManager(assembly);

            DisplayAttribute display = new() { ResourceType = assembly.GetType("Test.Translations.Strings+Texts"), Name = "emailLabel" };
            Assert.Equal("E-mail", display.GetName());
        }

        [Fact]
        public void ShouldNotGenerateAccessorsWithOnlyDeclareKeys()
        {
            string source = Generate("AnnotationsOnlyKeys.cfg", accessors: false);

            // The configuration itself asks for the accessors, which also proves that the option is read from the configuration file. With onlyDeclareKeys there are no units to read, so the option gives way.
            Assert.Equal(-1, source.IndexOf("class Texts", StringComparison.Ordinal));
            Assert.NotEqual(-1, source.IndexOf("public const string emailLabelKey", StringComparison.Ordinal));

            Compile(source);
        }

        [Fact]
        public void ShouldReportAConflictWithTheNameOfTheAccessorClass()
        {
            // The configuration file switches the accessors on and contains a key named after the class of accessors.
            string source = Generate("AccessorCollision.cfg", accessors: false);

            Assert.NotEqual(-1, source.IndexOf("#warning Tlumach did not generate the 'Texts' class", StringComparison.Ordinal));
            Assert.Equal(-1, source.IndexOf("public static class Texts", StringComparison.Ordinal));

            // The conflict must not break the build; the generated code still compiles, only without the accessors.
            Compile(source);
        }

        [Fact]
        public void ShouldUseTheConfiguredNameOfTheAccessorClass()
        {
            Dictionary<string, string> options = new(StringComparer.OrdinalIgnoreCase)
            {
                ["UsingNamespace"] = "Tlumach",
                ["StringAccessorsClass"] = "Labels",
            };

            string source = GeneratorTests.TestGenerator.GenerateClass(Path.Combine(TestFilesPath, "AccessorCollision.cfg"), TestFilesPath, options)!;

            Assert.NotEqual(-1, source.IndexOf("public static class Labels", StringComparison.Ordinal));
            Assert.Equal(-1, source.IndexOf("#warning", StringComparison.Ordinal));

            Compile(source);
        }

        [Fact]
        public void ShouldReadTheAmbientCultureInAmbientMode()
        {
            Dictionary<string, string> options = new(StringComparer.OrdinalIgnoreCase)
            {
                ["UsingNamespace"] = "Tlumach",
                ["CreateStringAccessors"] = "true",
                ["StringAccessorsCulture"] = "ambient",
            };

            string source = GeneratorTests.TestGenerator.GenerateClass(Path.Combine(TestFilesPath, "Annotations.cfg"), TestFilesPath, options)!;

            Assert.NotEqual(-1, source.IndexOf("public static string emailLabel => global::Test.Translations.Strings.emailLabel.GetValue(System.Globalization.CultureInfo.CurrentCulture);", StringComparison.Ordinal));

            Assembly assembly = Compile(source);
            TranslationManager manager = PrepareManager(assembly);

            // The culture of the manager is left alone; only the culture of the thread decides.
            DisplayAttribute display = new() { ResourceType = assembly.GetType("Test.Translations.Strings+Texts"), Name = "emailLabel" };

            CultureInfo original = CultureInfo.CurrentCulture;
            try
            {
                CultureInfo.CurrentCulture = new CultureInfo("de");
                Assert.Equal("E-Mail-Adresse", display.GetName());

                CultureInfo.CurrentCulture = CultureInfo.InvariantCulture;
                Assert.Equal("E-mail", display.GetName());
            }
            finally
            {
                CultureInfo.CurrentCulture = original;
            }

            Assert.Equal(CultureInfo.InvariantCulture.Name, manager.CurrentCulture.Name);
        }

        [Fact]
        public void ShouldSwitchTheAccessorsOnFromEitherSource()
        {
            // The build option alone.
            Assert.NotEqual(-1, Generate("Annotations.cfg", accessors: true).IndexOf("public static class Texts", StringComparison.Ordinal));

            // The configuration file alone. AnnotationsOnlyKeys.cfg carries the key, but with onlyDeclareKeys, so AccessorCollision.cfg with another class name is used instead.
            Dictionary<string, string> options = new(StringComparer.OrdinalIgnoreCase)
            {
                ["UsingNamespace"] = "Tlumach",
                ["StringAccessorsClass"] = "Labels",
            };
            Assert.NotEqual(-1, GeneratorTests.TestGenerator.GenerateClass(Path.Combine(TestFilesPath, "AccessorCollision.cfg"), TestFilesPath, options)!.IndexOf("public static class Labels", StringComparison.Ordinal));

            // Neither source.
            Assert.Equal(-1, Generate("Annotations.cfg", accessors: false).IndexOf("public static class Texts", StringComparison.Ordinal));

            // The build option set to false while the configuration file sets the key: the two sources are combined with a logical or, exactly as the older options are.
            Dictionary<string, string> mixed = new(StringComparer.OrdinalIgnoreCase)
            {
                ["UsingNamespace"] = "Tlumach",
                ["CreateStringAccessors"] = "false",
                ["StringAccessorsClass"] = "Labels",
            };
            Assert.NotEqual(-1, GeneratorTests.TestGenerator.GenerateClass(Path.Combine(TestFilesPath, "AccessorCollision.cfg"), TestFilesPath, mixed)!.IndexOf("public static class Labels", StringComparison.Ordinal));
        }

        internal static string Generate(string configFile, bool accessors)
        {
            Dictionary<string, string> options = new(StringComparer.OrdinalIgnoreCase)
            {
                ["UsingNamespace"] = "Tlumach",
            };

            if (accessors)
                options["CreateStringAccessors"] = "true";

            string? result = GeneratorTests.TestGenerator.GenerateClass(Path.Combine(TestFilesPath, configFile), TestFilesPath, options);
            Assert.NotNull(result);

            return result;
        }

        internal static Assembly Compile(string source) => Compile(new[] { source });

        internal static Assembly Compile(IEnumerable<string> sources)
        {
            var (ok, diags, assembly) = RoslynCompileHelper.CompileToAssembly(sources);

            if (!ok)
            {
                string message = string.Join(
                    Environment.NewLine,
                    diags.Where(d => d.Severity >= Microsoft.CodeAnalysis.DiagnosticSeverity.Warning).Select(d => d.ToString()));
                Assert.True(ok, "Compilation failed:" + Environment.NewLine + message);
            }

            Assert.NotNull(assembly);

            return assembly;
        }

        internal static TranslationManager PrepareManager(Assembly assembly)
        {
            TranslationManager? manager = GeneratorTests.GetTranslationManager(assembly);
            Assert.NotNull(manager);

            manager.LoadFromDisk = true;
            manager.TranslationsDirectory = TestFilesPath;
            manager.CurrentCulture = CultureInfo.InvariantCulture;

            return manager;
        }

        private static PropertyInfo AccessorProperty(Assembly assembly, string typeName, string name)
        {
            Type? type = assembly.GetType(typeName);
            Assert.NotNull(type);
            Assert.True(type.IsVisible, "The class of accessors must be visible outside the assembly.");

            PropertyInfo? property = type.GetProperty(name, BindingFlags.Public | BindingFlags.Static);
            Assert.NotNull(property);

            return property;
        }
    }
}
