// <copyright file="BaseGenerator.cs" company="Allied Bits Ltd.">
//
// Copyright 2025 Allied Bits Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// </copyright>

using System.Text;

namespace Tlumach.Base
{
    public class BaseGenerator
    {
        private static string OwnName(string keyName)
        {
            int idx = keyName.IndexOf('.');
            if (idx == -1)
                return keyName;
            else
            if (idx == keyName.Length - 1)
                return string.Empty;
            else
                return keyName.Substring(idx + 1);
        }

        protected string? GenerateClass(string configFile, string projectDir, string usingNamespace)
        {
            if (configFile is null)
                throw new ArgumentNullException(nameof(configFile));

            string filename = configFile;

            TranslationConfiguration? configuration;

            // The config parser will parse configuration and will find the correct parser for the files referenced by the configuration
            BaseFileParser? parser = FileFormats.GetConfigParser(Path.GetExtension(filename.ToLowerInvariant()));
            if (parser is null)
                return null;

            TranslationTree? translationTree = parser.LoadTranslationStructure(filename, out configuration);

            if (configuration is null)
                throw new ParserLoadException(filename, $"Failed to load the configuration from '{filename}'");

            if (translationTree is null)
                throw new ParserLoadException(filename, $"Failed to load the default language file referenced by '{filename}'");

            if (string.IsNullOrEmpty(configuration.Namespace))
                throw new ParserConfigException(filename, $"The configuration file '{filename}' does not contain the namespace for the class to be generated, which must be specified in the '{TranslationConfiguration.KEY_GENERATED_NAMESPACE}' setting");

            if (string.IsNullOrEmpty(configuration.ClassName))
                throw new ParserConfigException(filename, $"The configuration file '{filename}' does not contain the name of the class to be generated, which must be specified in the '{TranslationConfiguration.KEY_GENERATED_CLASS}' setting");

            StringBuilder builder = new();

            builder.AppendLine("using System;\nusing System.Reflection;\n\n");
            builder.AppendLine("using Tlumach.Base;");
            if (!string.IsNullOrEmpty(usingNamespace))
                builder.Append("using ").Append(usingNamespace).AppendLine(";");
            builder.AppendLine("using Tlumach;");
            builder.AppendLine("namespace ").Append(configuration.Namespace).AppendLine(";");
            builder.AppendLine();
            builder.Append("// ").AppendLine(configuration.DefaultFile);
            builder.AppendLine("// <auto-generated/>");
            builder.Append("public static class ").Append(configuration.ClassName).AppendLine();
            builder.AppendLine("{");
            if (!string.IsNullOrEmpty(configuration.DefaultFileLocale))
                builder.Append("    private static string _defaultFileLocale = \"").Append(configuration.DefaultFileLocale).AppendLine("\";");
            else
                builder.AppendLine("    private static string _defaultFileLocale = null;");
            builder.AppendLine();
            builder.Append("    private static TranslationConfiguration _translationConfiguration = new TranslationConfiguration(typeof(").Append(configuration.ClassName).Append(").Assembly, \"").Append(configuration.DefaultFile).AppendLine("\", _defaultFileLocale);\n");
            builder.AppendLine("{").Append("    public static TranslationManager TranslationManager {get; } = new TranslationManager();");

            EmitGroupUnits(builder, translationTree, translationTree.RootNode, 1);

            builder.AppendLine("}");

            return builder.ToString();
        }

        protected void EmitGroupUnits(StringBuilder builder, TranslationTree translationTree, TranslationTreeNode node, int offset)
        {
            if (builder is null)
                throw new ArgumentNullException(nameof(builder));
            if (node is null)
                throw new ArgumentNullException(nameof(node));

            var offsetString = new string(' ', offset << 2);

            foreach (var key in node.Keys)
            {
                builder.AppendLine();
                builder.Append(offsetString).Append("public static TranslationUnit ").Append(OwnName(key)).Append(" = new TranslationUnit(TranslationManager, _translationConfiguration, \"").Append(key).AppendLine("\");");
            }

            foreach (var child in node.ChildNodes.Keys.OrderBy(x => x, StringComparer.OrdinalIgnoreCase))
            {
                builder.AppendLine();
                builder.Append(offsetString).Append("public static class ").Append(node.ChildNodes[child].Name).AppendLine();
                builder.Append(offsetString).AppendLine("{");
                EmitGroupUnits(builder, translationTree, node.ChildNodes[child], offset + 1);
                builder.Append(offsetString).AppendLine("}");
            }
        }
    }
}
