// <copyright file="TranslationUnit.cs" company="Allied Bits Ltd.">
//
// Copyright 2025 Allied Bits Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// </copyright>

using System.Diagnostics;

using Tlumach.Base;

namespace Tlumach;

/// <summary>
/// <para>Represents a unit of translation - a unit of text (a word, a phrase, a sentence, etc.) in a translation accessible using a unique key.</para>
/// <para>This class is used in generated code except when using Avalonia, WinUI or UWP (those have own TranslationUnit classes in the corresponding assemblies).</para>
/// </summary>
[DebuggerDisplay("{DebuggerDisplay,nq}")]
public class TranslationUnit : BaseTranslationUnit, IDisposable
{
    private string? _currentValue;

    private bool _disposedValue;

    /// <summary>
    /// Gets or sets the indicator that tells the class that it may cache the string values without going for them to TranslationManager every time.
    /// </summary>
    public static bool CacheValues { get; set; } = true;

    /// <summary>
    /// Gets the value of the unit according to the current culture set in the associated translation manager.
    /// </summary>
    public string CurrentValue
    {
        get
        {
            if (CacheValues)
            {
                if (_currentValue is null)
                    _currentValue = GetValue(TranslationManager.CurrentCulture);

                return _currentValue;
            }
            else
            {
                return GetValue(TranslationManager.CurrentCulture);
            }
        }
    }

    /// <summary>
    /// Fires when the <see cref="NotifyPlaceholdersUpdated"/> method is called to notify listeners (mostly, XAML bindings) that they need to update.
    /// <para>Does not fire when the culture of the translation manager referenced by the <see cref="BaseTranslationUnit.TranslationManager"/> property changes.
    /// If an application needs, it can subscribe to the <see cref="TranslationManager.OnCultureChanged" /> event.</para>
    /// </summary>
    public event EventHandler<EventArgs>? OnChange;

    /// <summary>
    /// Initializes a new instance of the <see cref="TranslationUnit"/> class.
    /// <para>For internal use. This constructor is used by <seealso cref="UntranslatedUnit"/>.</para>
    /// </summary>
    /// <param name="translationManager">The translation manager to which the unit is bound.</param>
    /// <param name="translationConfiguration">The translation configuration used to create the unit.</param>
    /// <param name="containsPlaceholders">An indicator of whether the unit contains placeholders.</param>
    protected TranslationUnit(TranslationManager translationManager, TranslationConfiguration translationConfiguration, bool containsPlaceholders)
        : base(translationManager, translationConfiguration, containsPlaceholders)
    {
        if (TranslationManager != TranslationManager.Empty)
            TranslationManager.OnCultureChanged += TranslationManager_OnCultureChanged;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="TranslationUnit"/> class.
    /// <para>For internal use. This constructor is used by the code generated by Generator.</para>
    /// </summary>
    /// <param name="translationManager">The translation manager to which the unit is bound.</param>
    /// <param name="translationConfiguration">The translation configuration used to create the unit.</param>
    /// <param name="key">The key of the unit.</param>
    /// <param name="containsPlaceholders">An indicator of whether the unit contains placeholders.</param>
    public TranslationUnit(TranslationManager translationManager, TranslationConfiguration translationConfiguration, string key, bool containsPlaceholders)
        : base(translationManager, translationConfiguration, key, containsPlaceholders)
    {
        if (TranslationManager != TranslationManager.Empty)
            TranslationManager.OnCultureChanged += TranslationManager_OnCultureChanged;
    }

    public override string ToString() => CurrentValue ?? string.Empty;

    public static implicit operator string(TranslationUnit unit)
        => unit?.ToString() ?? string.Empty;

    private string DebuggerDisplay() => $"Translation unit '{Key}': '{CurrentValue ?? "(No value)"}'";

    /// <summary>
    /// Notifies XAML bindings that they need to request a new value and update the controls.
    /// </summary>
    public override void NotifyPlaceholdersUpdated()
    {
        _currentValue = null;
        OnChange?.Invoke(this, EventArgs.Empty);
    }

    private void TranslationManager_OnCultureChanged(object? sender, CultureChangedEventArgs e)
    {
        _currentValue = null;
    }

    protected virtual void Dispose(bool disposing)
    {
        if (!_disposedValue)
        {
            if (disposing)
            {
#pragma warning disable S1066 // Mergeable "if" statements should be combined
                if (TranslationManager != TranslationManager.Empty)
                    TranslationManager.OnCultureChanged -= TranslationManager_OnCultureChanged;
#pragma warning restore S1066 // Mergeable "if" statements should be combined
            }

            _disposedValue = true;
        }
    }

    public void Dispose()
    {
        Dispose(disposing: true);
        GC.SuppressFinalize(this);
    }
}
